apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cast-off.fullname" . }}-{{ .Values.config.ciliumNamespace }}
  namespace: {{ .Values.config.ciliumNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "cast-off.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
