{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cast-off.serviceAccountName" . }}
  namespace: {{ .Values.config.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cast-off.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
